apiVersion: apps/v1
kind: Statefulset
metadata:
  name: coffee-db
  namespace: coffee-app

spec:
  serviceName: "db-service"
  replicas: 1
  selector:
    matchLabels:
      app: coffee-db
  template:
    metadata:
      labels:
        app: coffee-db

    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: coffee-Secrets
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                name: coffee-Secrets
                key: PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: coffee-config
                  key: DB_NAME

          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
            - name: schema-volume
              mountPath: /docker-entrypoint-initd.d/schema.sql
              subPath: schema.sql

          volumes:
            - name: postgres-storage
              persistentVolumeClaim:
                claimName: postgres-pvc

            - name: schema-volume
              configMap:
                name: db-schema-config
