apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: coffee-app

spec:
  selector:
    app: coffee-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  #using NodePort ; use LoadBalancer on cloud
  type: NodePort
